[project]
name = "breezestylesheets"
version = "0.2.0"
description = "Configurable Breeze and BreezeDark-like stylesheets for Qt Applications."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.5.3,<3.0.0",
    "pydantic-extra-types>=2.3.0,<3.0.0",
]
authors = [
  {name = "Colin Duquesnoy"},
  { name = "Alex Huszagh", email = "ahuszagh@gmail.com" },
]
maintainers = [
  { name = "Alex Huszagh", email = "ahuszagh@gmail.com" },
]
license = { "file" = "LICENSE.md" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Environment :: X11 Applications :: Qt",
]
keywords = ["qt", "gui", "stylesheets"]

[project.urls]
Homepage = "https://github.com/Alexhuszagh/BreezeStyleSheets"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/Alexhuszagh/BreezeStyleSheets.git"
"Bug Tracker" = "https://github.com/Alexhuszagh/BreezeStyleSheets/issues"
Changelog = "https://github.com/Alexhuszagh/BreezeStyleSheets/main/CHANGELOG.md"

[project.optional-dependencies]
# TODO: Add optional dependencies on Qt5, Qt6, etc. when we actually
# make this a full package
yaml = [
    "pyyaml>=6.0.1,<7.0.0",
]
toml = [
    "tomli>=2.0.1,<3.0.0; python_version < '3.11'",
]
xml = [
    "xml2dict>=0.2.2,<0.3.0",
]

[dependency-groups]
lint = [
    "black>=25.9.0,<26.0.0",
    "flake8>=7.0.0,<8.0.0",
    "isort>=5.11.5,<6.0.0",
    "pylint>=3.3.8,<4.0.0",
    "pyupgrade>=3.20.0,<4.0.0",
    "ruff>=0.13.2,<0.14.0",
]
test = [
    "coverage>=7.2.7,<8.0.0",
    "coverage-badge>=1.1.2,<2.0.0",
    "pytest>=7.4.4,<8.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "pytest-html>=3.2.0,<4.0.0",
    "tox>=4.8.0,<5.0.0",
]
type = [
    "mypy>=1.4.1,<2.0.0",
    "pyright>=1.1.405,<2.0.0",
    "types-pyyaml>=6.0.12.20250915,<7.0.0.0",
]

[tool.setuptools]
py-modules = ["breezestylesheets"]

[tool.uv.dependency-groups]
lint = { requires-python = ">=3.11" }

[tool.uv]
add-bounds = "major"

[tool.black]
target-version = ["py310"]
line-length = 110
color = true
skip-string-normalization = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.isort]
py_version = 310
line_length = 110
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true
known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
no_lines_before = ["TYPING", "STDLIB", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pylint.main]
fail-under = 10.0
ignore = [".venv", "dist", ".git", "htmlcov", "venv"]
ignore-patterns = ["^\\.#"]
jobs = 0
limit-inference-results = 100
persistent = true
py-version = "3.9"
suggestion-mode = true

[tool.pylint.basic]
argument-naming-style = "snake_case"
attr-naming-style = "snake_case"
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]
class-attribute-naming-style = "any"
class-const-naming-style = "UPPER_CASE"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"
docstring-min-length = -1
function-naming-style = "snake_case"
good-names = ["i", "j", "k", "ex", "Run", "_"]
inlinevar-naming-style = "any"
method-naming-style = "snake_case"
module-naming-style = "snake_case"
no-docstring-rgx = "^_"
property-classes = ["abc.abstractproperty"]
variable-naming-style = "snake_case"

[tool.pylint.classes]
defining-attr-methods = ["__init__", "__new__", "setUp", "asyncSetUp", "__post_init__"]
exclude-protected = ["_asdict", "_fields", "_replace", "_source", "_make", "os._exit"]
valid-classmethod-first-arg = ["cls"]
valid-metaclass-classmethod-first-arg = ["mcs"]

[tool.pylint.design]
max-args = 15
max-attributes = 24
max-bool-expr = 10
max-branches = 24
max-locals = 20
max-parents = 12
max-public-methods = 40
max-returns = 15
max-statements = 50
min-public-methods = 0
max-positional-arguments = 8

[tool.pylint.exceptions]
overgeneral-exceptions = ["builtins.BaseException", "builtins.Exception"]

[tool.pylint.format]
ignore-long-lines = "^\\s*(# )?<?https?://\\S+>?$"
indent-after-paren = 4
indent-string = "    "
max-line-length = 110
max-module-lines = 2500

[tool.pylint.imports]
known-third-party = ["enchant"]

[tool.pylint.logging]
logging-format-style = "old"
logging-modules = ["logging"]

[tool.pylint."messages control"]
confidence = ["HIGH", "CONTROL_FLOW", "INFERENCE", "INFERENCE_FAILURE", "UNDEFINED"]
disable = ["raw-checker-failed", "bad-inline-option", "locally-disabled", "file-ignored", "suppressed-message", "useless-suppression", "deprecated-pragma", "use-symbolic-message-instead", "use-implicit-booleaness-not-comparison-to-string", "use-implicit-booleaness-not-comparison-to-zero", "import-outside-toplevel", "broad-exception-caught", "too-few-public-methods", "global-statement", "c-extension-no-member", "too-many-instance-attributes", "invalid-name", "attribute-defined-outside-init", "unnecessary-lambda-assignment", "fixme"]

[tool.pylint.method_args]
timeout-methods = ["requests.api.delete", "requests.api.get", "requests.api.head", "requests.api.options", "requests.api.patch", "requests.api.post", "requests.api.put", "requests.api.request"]

[tool.pylint.miscellaneous]
notes = ["FIXME", "XXX", "TODO"]

[tool.pylint.refactoring]
max-nested-blocks = 5
never-returning-functions = ["sys.exit", "argparse.parse_error"]
suggest-join-with-non-empty-separator = true

[tool.pylint.reports]
evaluation = "max(0, 0 if fatal else 10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10))"
score = true

[tool.pylint.similarities]
ignore-comments = true
ignore-docstrings = true
ignore-imports = true
ignore-signatures = true
min-similarity-lines = 15

[tool.pylint.spelling]
max-spelling-suggestions = 4
spelling-ignore-comment-directives = "fmt: on,fmt: off,noqa:,noqa,nosec,isort:skip,mypy:"

[tool.pylint.typecheck]
contextmanager-decorators = ["contextlib.contextmanager"]
ignore-none = true
ignore-on-opaque-inference = true
ignored-checks-for-mixins = ["no-member", "not-async-context-manager", "not-context-manager", "attribute-defined-outside-init"]
ignored-classes = ["optparse.Values", "thread._local", "_thread._local", "argparse.Namespace"]
missing-member-hint = true
missing-member-hint-distance = 1
missing-member-max-choices = 1
mixin-class-rgx = ".*[Mm]ixin"

[tool.pylint.variables]
allow-global-unused-variables = true
callbacks = ["cb_", "_cb"]
dummy-variables-rgx = "_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_"
ignored-argument-names = "_.*|^ignored_|^unused_"
redefining-builtins-modules = ["six.moves", "past.builtins", "future.builtins", "builtins", "io"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=breezestylesheets --cov-report html"

[tool.pyright]
include = ["breezestylesheets"] # TODO: "example", "test" once base has been implemented

[tool.mypy]
packages = ["breezestylesheets"]

[tool.ruff]
line-length = 110
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
ignore = ["E203", "E226"]
select = ["E", "F", "N", "W", "UP"]
preview = true

[tool.ruff.format]
quote-style = 'single'
line-ending = 'lf'
preview = true

[tool.tox]
requires = ["tox>=4.19"]
env_list = ["3.9", "3.10", "3.11", "3.12", "3.13", "lint", "type"]
isolated_build = true

[tool.tox.env_run_base]
description = "Run test suite under {base_python}"
commands = []  # TODO: Fix to support ["pytest"], bug with UTF8 start byte
dependency_groups = ["test"]

[tool.tox.env.type]
description = "Run test suite under {base_python}"
commands = [["pyright"]]  # TODO: Fix the `, ["mypy"]
dependency_groups = ["test", "type"]

[tool.tox.env.lint]
description = "Run test suite under {base_python}"
commands = [
  ["black", "--check", "breezestylesheets/"],  # TODO: "example/", "test/"
  ["isort", "--check-only", "breezestylesheets/"], # TODO: "example/", "test/"
  ["ruff", "check", "breezestylesheets/"], # TODO: "example/", "test/"
  ["pylint", "breezestylesheets/"], # TODO: "example/", "test/"
  ["flake8"],
]
dependency_groups = ["test", "lint"]
