from typing import TYPE_CHECKING

from example._util.assertions import nonnull
from example._util.style import style_icon
from .cli import ARGS, STANDARD_ICONS, Qt

if TYPE_CHECKING:
    from PyQt6 import QtGui, QtWidgets


def close_icon(widget: "QtWidgets.QWidget") -> "QtGui.QIcon":
    """Get the close icon depending on the stylesheet."""
    style = widget.style()
    assert style is not None
    pixmap = Qt.QtWidgets.QStyle.StandardPixmap.SP_DockWidgetCloseButton
    return style_icon(style, Qt, STANDARD_ICONS, ARGS, pixmap, widget=widget)


class Ui:
    def setup(self, window: "QtWidgets.QMainWindow") -> None:
        window.setObjectName("MainWindow")
        self.central_widget = Qt.QtWidgets.QWidget(window)
        self.central_widget.setObjectName("centralwidget")
        self.vertical_layout_5 = Qt.QtWidgets.QVBoxLayout(self.central_widget)
        self.vertical_layout_5.setObjectName("verticalLayout_5")
        self.tab_widget = Qt.QtWidgets.QTabWidget(self.central_widget)
        self.tab_widget.setTabPosition(Qt.QtWidgets.QTabWidget.TabPosition.East)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setObjectName("tabWidget")
        self.tab = Qt.QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.grid_layout = Qt.QtWidgets.QGridLayout(self.tab)
        self.grid_layout.setObjectName("gridLayout")
        self.group_box = Qt.QtWidgets.QGroupBox(self.tab)
        self.group_box.setObjectName("groupBox")
        self.vertical_layout_3 = Qt.QtWidgets.QVBoxLayout(self.group_box)
        self.vertical_layout_3.setObjectName("verticalLayout_3")
        self.tool_box = Qt.QtWidgets.QToolBox(self.group_box)
        self.tool_box.setObjectName("toolBox")
        self.page = Qt.QtWidgets.QWidget()
        self.page.setGeometry(Qt.QtCore.QRect(0, 0, 718, 227))
        self.page.setObjectName("page")
        self.grid_layout_4 = Qt.QtWidgets.QGridLayout(self.page)
        self.grid_layout_4.setObjectName("gridLayout_4")
        self.line_edit = Qt.QtWidgets.QLineEdit(self.page)
        self.line_edit.setObjectName("lineEdit")
        self.grid_layout_4.addWidget(self.line_edit, 0, 0, 1, 1)
        self.tool_box.addItem(self.page, "")
        self.page_2 = Qt.QtWidgets.QWidget()
        self.page_2.setGeometry(Qt.QtCore.QRect(0, 0, 718, 227))
        self.page_2.setObjectName("page_2")
        self.grid_layout_5 = Qt.QtWidgets.QGridLayout(self.page_2)
        self.grid_layout_5.setObjectName("gridLayout_5")
        self.list_widget = Qt.QtWidgets.QListWidget(self.page_2)
        self.list_widget.setObjectName("listWidget")
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.list_widget.addItem(Qt.QtWidgets.QListWidgetItem())
        self.grid_layout_5.addWidget(self.list_widget, 0, 0, 1, 1)
        self.tool_box.addItem(self.page_2, "")
        self.vertical_layout_3.addWidget(self.tool_box)
        self.grid_layout.addWidget(self.group_box, 1, 0, 1, 1)
        self.tab_widget_2 = Qt.QtWidgets.QTabWidget(self.tab)
        self.tab_widget_2.setObjectName("tabWidget_2")
        self.tab_3 = Qt.QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.grid_layout_6 = Qt.QtWidgets.QGridLayout(self.tab_3)
        self.grid_layout_6.setObjectName("gridLayout_6")
        self.checkable_button = Qt.QtWidgets.QPushButton(self.tab_3)
        self.checkable_button.setCheckable(True)
        self.checkable_button.setChecked(True)
        self.checkable_button.setObjectName("checkableButton")
        self.grid_layout_6.addWidget(self.checkable_button, 1, 0, 1, 1)
        self.push_button = Qt.QtWidgets.QPushButton(self.tab_3)
        self.push_button.setObjectName("pushButton")
        self.push_button.setToolTip("Sample Tooltip1")
        self.grid_layout_6.addWidget(self.push_button, 0, 0, 1, 1)
        self.push_button_5 = Qt.QtWidgets.QPushButton(self.tab_3)
        self.push_button_5.setObjectName("pushButton_5")
        self.grid_layout_6.addWidget(self.push_button_5, 2, 0, 1, 1)
        self.tab_widget_2.addTab(self.tab_3, "")
        self.tab_5 = Qt.QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.grid_layout_7 = Qt.QtWidgets.QGridLayout(self.tab_5)
        self.grid_layout_7.setObjectName("gridLayout_7")
        self.table_widget = Qt.QtWidgets.QTableWidget(self.tab_5)
        self.table_widget.setObjectName("tableWidget")
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(4)
        self.table_widget.setVerticalHeaderItem(0, Qt.QtWidgets.QTableWidgetItem())
        self.table_widget.setVerticalHeaderItem(1, Qt.QtWidgets.QTableWidgetItem())
        self.table_widget.setVerticalHeaderItem(2, Qt.QtWidgets.QTableWidgetItem())
        self.table_widget.setVerticalHeaderItem(3, Qt.QtWidgets.QTableWidgetItem())
        self.table_widget.setHorizontalHeaderItem(0, Qt.QtWidgets.QTableWidgetItem())
        self.table_widget.setHorizontalHeaderItem(1, Qt.QtWidgets.QTableWidgetItem())
        self.grid_layout_7.addWidget(self.table_widget, 0, 0, 1, 1)
        self.tab_widget_2.addTab(self.tab_5, "")
        self.tab_4 = Qt.QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.vertical_layout_6 = Qt.QtWidgets.QVBoxLayout(self.tab_4)
        self.calendar = Qt.QtWidgets.QCalendarWidget(self.tab_4)
        self.calendar.setGridVisible(True)
        self.vertical_layout_6.addWidget(self.calendar)
        self.tab_widget_2.addTab(self.tab_4, "")
        self.tab_5v2 = Qt.QtWidgets.QWidget()
        self.tab_5v2.setObjectName("tab_5v2")
        self.vertical_layout_7 = Qt.QtWidgets.QVBoxLayout(self.tab_5v2)
        self.table_widget_2 = Qt.QtWidgets.QTableWidget(self.tab_5v2)
        self.table_widget_2.setColumnCount(100)
        self.table_widget_2.setRowCount(1)
        self.table_widget_2.setVerticalHeaderItem(0, Qt.QtWidgets.QTableWidgetItem("Row 1"))
        for index in range(100):
            self.table_widget_2.setHorizontalHeaderItem(
                index, Qt.QtWidgets.QTableWidgetItem(f"Column {index + 1}")
            )
        self.vertical_layout_7.addWidget(self.table_widget_2)
        self.tab_widget_2.addTab(self.tab_5v2, "")
        self.tab_6v2 = Qt.QtWidgets.QWidget()
        self.tab_6v2.setObjectName("tab_6v2")
        self.vertical_layout_8 = Qt.QtWidgets.QVBoxLayout(self.tab_6v2)
        splitter = Qt.QtWidgets.QSplitter(self.tab_6v2)
        splitter.addWidget(Qt.QtWidgets.QListWidget(self.tab_6v2))
        tree = Qt.QtWidgets.QTreeWidget(self.tab_6v2)
        _item_12 = Qt.QtWidgets.QTreeWidgetItem(tree, ["Row 1"])
        splitter.addWidget(tree)
        splitter.addWidget(Qt.QtWidgets.QTextEdit(self.tab_6v2))
        self.vertical_layout_8.addWidget(splitter)
        self.tab_widget_2.addTab(self.tab_6v2, "")
        self.grid_layout.addWidget(self.tab_widget_2, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = Qt.QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.grid_layout_2 = Qt.QtWidgets.QGridLayout(self.tab_2)
        self.grid_layout_2.setObjectName("gridLayout_2")
        self.group_box_2 = Qt.QtWidgets.QGroupBox(self.tab_2)
        self.group_box_2.setObjectName("groupBox_2")
        self.vertical_layout_4 = Qt.QtWidgets.QVBoxLayout(self.group_box_2)
        self.vertical_layout_4.setObjectName("verticalLayout_4")
        self.label = Qt.QtWidgets.QLabel(self.group_box_2)
        self.label.setObjectName("label")
        self.vertical_layout_4.addWidget(self.label)
        self.radio_button = Qt.QtWidgets.QRadioButton(self.group_box_2)
        self.radio_button.setObjectName("radioButton")
        self.vertical_layout_4.addWidget(self.radio_button)
        self.check_box = Qt.QtWidgets.QCheckBox(self.group_box_2)
        self.check_box.setObjectName("checkBox")
        self.vertical_layout_4.addWidget(self.check_box)
        self.check_box_2 = Qt.QtWidgets.QCheckBox(self.group_box_2)
        self.check_box_2.setTristate(True)
        self.check_box_2.setObjectName("checkBox_2")
        self.vertical_layout_4.addWidget(self.check_box_2)
        self.check_box_3 = Qt.QtWidgets.QCheckBox(self.group_box_2)
        self.check_box_3.setEnabled(False)
        self.check_box_3.setObjectName("checkBox_3")
        self.vertical_layout_4.addWidget(self.check_box_3)
        self.tree_widget = Qt.QtWidgets.QTreeWidget(self.group_box_2)
        self.tree_widget.setObjectName("treeWidget")
        _item_0 = Qt.QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = Qt.QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_2 = Qt.QtWidgets.QTreeWidgetItem(item_1)
        item_2.setText(0, "subitem")
        item_3 = Qt.QtWidgets.QTreeWidgetItem(item_2, ["Row 2.1"])
        item_3.setFlags(item_3.flags() | Qt.QtCore.Qt.ItemFlag.ItemIsUserCheckable)
        item_3.setCheckState(0, Qt.QtCore.Qt.CheckState.Unchecked)
        item_4 = Qt.QtWidgets.QTreeWidgetItem(item_2, ["Row 2.2"])
        item_5 = Qt.QtWidgets.QTreeWidgetItem(item_4, ["Row 2.2.1"])
        _item_6 = Qt.QtWidgets.QTreeWidgetItem(item_5, ["Row 2.2.1.1"])
        item_7 = Qt.QtWidgets.QTreeWidgetItem(item_5, ["Row 2.2.1.2"])
        item_3.setFlags(item_7.flags() | Qt.QtCore.Qt.ItemFlag.ItemIsUserCheckable)
        item_7.setCheckState(0, Qt.QtCore.Qt.CheckState.Checked)
        item_8 = Qt.QtWidgets.QTreeWidgetItem(item_2, ["Row 2.3"])
        item_8.setFlags(item_8.flags() | Qt.QtCore.Qt.ItemFlag.ItemIsUserTristate)
        item_8.setCheckState(0, Qt.QtCore.Qt.CheckState.PartiallyChecked)
        item_9 = Qt.QtWidgets.QTreeWidgetItem(self.tree_widget, ["Row 3"])
        _item_10 = Qt.QtWidgets.QTreeWidgetItem(item_9, ["Row 3.1"])
        _item_11 = Qt.QtWidgets.QTreeWidgetItem(self.tree_widget, ["Row 4"])
        self.vertical_layout_4.addWidget(self.tree_widget)
        self.grid_layout_2.addWidget(self.group_box_2, 0, 0, 1, 1)
        self.tab_3v2 = Qt.QtWidgets.QWidget()
        self.tab_3v2.setObjectName("tab_3v2")
        self.grid_layout_3v2 = Qt.QtWidgets.QGridLayout(self.tab_3v2)
        self.grid_layout_3v2.setObjectName("gridLayout_3v2")
        self.group_box_3v2 = Qt.QtWidgets.QGroupBox(self.tab_3v2)
        self.group_box_3v2.setObjectName("groupBox_3v2")
        self.vertical_layout_4v2 = Qt.QtWidgets.QVBoxLayout(self.group_box_3v2)
        self.vertical_layout_4v2.setObjectName("verticalLayout_4v2")
        self.tab_widget3 = Qt.QtWidgets.QTabWidget(self.tab_3v2)
        self.tab_widget3.setTabShape(Qt.QtWidgets.QTabWidget.TabShape.Triangular)
        self.grid_layout_3v2.setObjectName("tabWidget3")
        self.tab_1v3 = Qt.QtWidgets.QWidget()
        self.tab_2v3 = Qt.QtWidgets.QWidget()
        self.tab_3v3 = Qt.QtWidgets.QWidget()
        self.tab_widget3.addTab(self.tab_1v3, "Tab 1")
        self.tab_widget3.addTab(self.tab_2v3, "Tab 2")
        self.tab_widget3.addTab(self.tab_3v3, "Tab 3")
        self.vertical_layout_6 = Qt.QtWidgets.QVBoxLayout(self.tab_1v3)
        self.vertical_layout_6.setObjectName("verticalLayout_6")
        self.key_sequence = Qt.QtWidgets.QKeySequenceEdit(self.tab_1v3)
        self.vertical_layout_6.addWidget(self.key_sequence)
        self.line_3 = Qt.QtWidgets.QLineEdit(self.tab_1v3)
        completer = Qt.QtWidgets.QCompleter(["Fruit", "Fruits Basket", "Fruba"])
        self.line_3.setCompleter(completer)
        self.vertical_layout_6.addWidget(self.line_3)
        self.password = Qt.QtWidgets.QLineEdit("Sample", self.tab_1v3)
        self.password.setEchoMode(Qt.QtWidgets.QLineEdit.EchoMode.Password)
        self.vertical_layout_6.addWidget(self.password)
        self.clear_line = Qt.QtWidgets.QLineEdit("Sample", self.tab_1v3)
        self.clear_line.setClearButtonEnabled(True)
        self.vertical_layout_6.addWidget(self.clear_line)
        self.lcd = Qt.QtWidgets.QLCDNumber(3, self.tab_1v3)
        self.lcd.display(15)
        self.lcd.setFrameShape(Qt.QtWidgets.QFrame.Shape.NoFrame)
        self.lcd.setSegmentStyle(Qt.QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.vertical_layout_6.addWidget(self.lcd)
        self.vertical_layout_4v2.addWidget(self.tab_widget3, 0, Qt.QtCore.Qt.AlignmentFlag.AlignTop)
        self.grid_layout_3v2.addWidget(self.group_box_3v2, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_2, "")
        self.tab_widget.addTab(self.tab_3v2, "")
        self.vertical_layout_5.addWidget(self.tab_widget)
        self.horizontal_layout = Qt.QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontalLayout")
        self.push_button_2 = Qt.QtWidgets.QPushButton(self.central_widget)
        self.push_button_2.setObjectName("pushButton_2")
        self.push_button_2.setToolTip("Sample Tooltip2")
        self.horizontal_layout.addWidget(self.push_button_2)
        self.bt_delay_popup = Qt.QtWidgets.QToolButton(self.central_widget)
        self.bt_delay_popup.setObjectName("bt_delay_popup")
        self.horizontal_layout.addWidget(self.bt_delay_popup)
        self.bt_instant_popup = Qt.QtWidgets.QToolButton(self.central_widget)
        self.bt_instant_popup.setPopupMode(Qt.QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.bt_instant_popup.setObjectName("bt_instant_popup")
        self.horizontal_layout.addWidget(self.bt_instant_popup)
        self.bt_menu_button_popup = Qt.QtWidgets.QToolButton(self.central_widget)
        self.bt_menu_button_popup.setPopupMode(Qt.QtWidgets.QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.bt_menu_button_popup.setObjectName("bt_menu_button_popup")
        self.horizontal_layout.addWidget(self.bt_menu_button_popup)
        self.bt_auto_raise = Qt.QtWidgets.QToolButton(self.central_widget)
        self.bt_auto_raise.setAutoRaise(True)
        self.bt_auto_raise.setIcon(close_icon(self.bt_auto_raise))
        self.bt_auto_raise.setObjectName("bt_auto_raise")
        self.horizontal_layout.addWidget(self.bt_auto_raise)
        self.bt_arrow = Qt.QtWidgets.QToolButton(self.central_widget)
        self.bt_arrow.setAutoRaise(True)
        self.bt_arrow.setArrowType(Qt.QtCore.Qt.ArrowType.UpArrow)
        self.bt_arrow.setObjectName("bt_arrow")
        self.horizontal_layout.addWidget(self.bt_arrow)
        self.line_2 = Qt.QtWidgets.QFrame(self.central_widget)
        self.line_2.setFrameShape(Qt.QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(Qt.QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontal_layout.addWidget(self.line_2)
        self.push_button_3 = Qt.QtWidgets.QPushButton(self.central_widget)
        self.push_button_3.setEnabled(False)
        self.push_button_3.setObjectName("pushButton_3")
        self.push_button_3.setToolTip("Sample Tooltip3")
        self.horizontal_layout.addWidget(self.push_button_3)
        self.double_spin_box = Qt.QtWidgets.QDoubleSpinBox(self.central_widget)
        self.double_spin_box.setObjectName("doubleSpinBox")
        self.horizontal_layout.addWidget(self.double_spin_box)
        self.tool_button = Qt.QtWidgets.QToolButton(self.central_widget)
        self.tool_button.setPopupMode(Qt.QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.tool_button.setObjectName("toolButton")
        self.horizontal_layout.addWidget(self.tool_button)
        self.vertical_layout_5.addLayout(self.horizontal_layout)
        window.setCentralWidget(self.central_widget)
        self.menubar = Qt.QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(Qt.QtCore.QRect(0, 0, 1068, 29))
        self.menubar.setObjectName("menubar")
        self.menu_menu = Qt.QtWidgets.QMenu(self.menubar)
        self.menu_menu.setObjectName("menuMenu")
        self.menu_submenu_2 = Qt.QtWidgets.QMenu(self.menu_menu)
        self.menu_submenu_2.setObjectName("menuSubmenu_2")
        window.setMenuBar(self.menubar)
        self.statusbar = Qt.QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.dock_widget1 = Qt.QtWidgets.QDockWidget(window)
        self.dock_widget1.setObjectName("dockWidget1")
        self.dock_widget_contents = Qt.QtWidgets.QWidget()
        self.dock_widget_contents.setObjectName("dockWidgetContents")
        self.vertical_layout_2 = Qt.QtWidgets.QVBoxLayout(self.dock_widget_contents)
        self.vertical_layout_2.setObjectName("verticalLayout_2")
        self.vertical_layout = Qt.QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("verticalLayout")
        self.combo_box = Qt.QtWidgets.QComboBox(self.dock_widget_contents)
        self.combo_box.setObjectName("comboBox")
        self.combo_box.setEditable(True)
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.vertical_layout.addWidget(self.combo_box)
        self.horizontal_slider = Qt.QtWidgets.QSlider(self.dock_widget_contents)
        self.horizontal_slider.setOrientation(Qt.QtCore.Qt.Orientation.Horizontal)
        self.horizontal_slider.setObjectName("horizontalSlider")
        self.vertical_layout.addWidget(self.horizontal_slider)
        self.text_edit = Qt.QtWidgets.QTextEdit(self.dock_widget_contents)
        self.text_edit.setObjectName("textEdit")
        self.vertical_layout.addWidget(self.text_edit)
        self.line = Qt.QtWidgets.QFrame(self.dock_widget_contents)
        self.line.setFrameShape(Qt.QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(Qt.QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.vertical_layout.addWidget(self.line)
        self.progress_bar = Qt.QtWidgets.QProgressBar(self.dock_widget_contents)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progressBar")
        self.vertical_layout.addWidget(self.progress_bar)
        self.vertical_layout_2.addLayout(self.vertical_layout)
        self.frame = Qt.QtWidgets.QFrame(self.dock_widget_contents)
        self.frame.setMinimumSize(Qt.QtCore.QSize(0, 100))
        self.frame.setFrameShape(Qt.QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(Qt.QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.vertical_layout_2.addWidget(self.frame)
        self.dock_widget1.setWidget(self.dock_widget_contents)
        window.addDockWidget(Qt.QtCore.Qt.DockWidgetArea(1), self.dock_widget1)
        self.tool_bar = Qt.QtWidgets.QToolBar(window)
        self.tool_bar.setObjectName("toolBar")
        window.addToolBar(Qt.QtCore.Qt.ToolBarArea.TopToolBarArea, self.tool_bar)
        self.dock_widget2 = Qt.QtWidgets.QDockWidget(window)
        self.dock_widget2.setObjectName("dockWidget2")
        self.dock_widget_contents_2 = Qt.QtWidgets.QWidget()
        self.dock_widget_contents_2.setObjectName("dockWidgetContents_2")
        self.grid_layout_3 = Qt.QtWidgets.QGridLayout(self.dock_widget_contents_2)
        self.grid_layout_3.setObjectName("gridLayout_3")
        self.vertical_slider = Qt.QtWidgets.QSlider(self.dock_widget_contents_2)
        self.vertical_slider.setOrientation(Qt.QtCore.Qt.Orientation.Vertical)
        self.vertical_slider.setObjectName("verticalSlider")
        self.grid_layout_3.addWidget(self.vertical_slider, 0, 0, 1, 1)
        self.dock_widget2.setWidget(self.dock_widget_contents_2)
        window.addDockWidget(Qt.QtCore.Qt.DockWidgetArea(1), self.dock_widget2)
        self.action_action = Qt.QtGui.QAction(window)
        self.action_action.setObjectName("actionAction")
        self.action_sub_menu = Qt.QtGui.QAction(window)
        self.action_sub_menu.setObjectName("actionSub_menu")
        self.action_action_c = Qt.QtGui.QAction(window)
        self.action_action_c.setObjectName("actionAction_C")
        self.menu_submenu_2.addAction(self.action_sub_menu)
        self.menu_submenu_2.addAction(self.action_action_c)
        self.menu_menu.addAction(self.action_action)
        self.menu_menu.addAction(self.menu_submenu_2.menuAction())
        self.menubar.addAction(self.menu_menu.menuAction())
        self.tool_bar.addAction(self.action_action)
        self.tool_bar.addAction(self.action_sub_menu)

        self.retranslate_ui(window)
        self.tab_widget.setCurrentIndex(0)
        self.tool_box.setCurrentIndex(1)
        self.tab_widget_2.setCurrentIndex(0)
        Qt.QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.push_button, self.checkable_button)
        window.setTabOrder(self.checkable_button, self.push_button_5)
        window.setTabOrder(self.push_button_5, self.tab_widget_2)
        window.setTabOrder(self.tab_widget_2, self.table_widget)
        window.setTabOrder(self.table_widget, self.radio_button)
        window.setTabOrder(self.radio_button, self.check_box)
        window.setTabOrder(self.check_box, self.check_box_2)
        window.setTabOrder(self.check_box_2, self.tree_widget)
        window.setTabOrder(self.tree_widget, self.push_button_2)
        window.setTabOrder(self.push_button_2, self.bt_delay_popup)
        window.setTabOrder(self.bt_delay_popup, self.bt_instant_popup)
        window.setTabOrder(self.bt_instant_popup, self.bt_menu_button_popup)
        window.setTabOrder(self.bt_menu_button_popup, self.push_button_3)
        window.setTabOrder(self.push_button_3, self.double_spin_box)
        window.setTabOrder(self.double_spin_box, self.tool_button)
        window.setTabOrder(self.tool_button, self.combo_box)
        window.setTabOrder(self.combo_box, self.horizontal_slider)
        window.setTabOrder(self.horizontal_slider, self.text_edit)
        window.setTabOrder(self.text_edit, self.vertical_slider)
        window.setTabOrder(self.vertical_slider, self.tab_widget)
        window.setTabOrder(self.tab_widget, self.line_edit)
        window.setTabOrder(self.line_edit, self.list_widget)

    def retranslate_ui(self, window: "QtWidgets.QMainWindow") -> None:
        _translate = Qt.QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_box.setTitle(_translate("MainWindow", "ToolBox"))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.list_widget.setSortingEnabled(False)
        nonnull(self.list_widget.item(0)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(1)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(2)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(3)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(4)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(5)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(6)).setText(_translate("MainWindow", "New Item"))
        nonnull(self.list_widget.item(7)).setText(_translate("MainWindow", "New Item"))
        self.list_widget.setSortingEnabled(True)
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.checkable_button.setText(_translate("MainWindow", "Checkable button"))
        self.push_button.setText(_translate("MainWindow", "PushButton"))
        self.push_button_5.setText(_translate("MainWindow", "PushButton"))
        self.tab_widget_2.setTabText(self.tab_widget_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.table_widget.setSortingEnabled(False)
        nonnull(self.table_widget.verticalHeaderItem(0)).setText(_translate("MainWindow", "New Row"))
        nonnull(self.table_widget.verticalHeaderItem(1)).setText(_translate("MainWindow", "New Row"))
        nonnull(self.table_widget.verticalHeaderItem(2)).setText(_translate("MainWindow", "New Row"))
        nonnull(self.table_widget.verticalHeaderItem(3)).setText(_translate("MainWindow", "New Row"))
        nonnull(self.table_widget.horizontalHeaderItem(0)).setText(_translate("MainWindow", "New Column"))
        nonnull(self.table_widget.horizontalHeaderItem(1)).setText(_translate("MainWindow", "New Column 2"))
        self.table_widget.setSortingEnabled(True)
        self.tab_widget_2.setTabText(self.tab_widget_2.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.tab_widget_2.setTabText(self.tab_widget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tab_widget_2.setTabText(
            self.tab_widget_2.indexOf(self.tab_5v2), _translate("MainWindow", "Tab 3")
        )
        self.tab_widget_2.setTabText(
            self.tab_widget_2.indexOf(self.tab_6v2), _translate("MainWindow", "Tab 4")
        )
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.group_box_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.radio_button.setText(_translate("MainWindow", "RadioB&utton"))
        self.check_box.setText(_translate("MainWindow", "CheckBox"))
        self.check_box_2.setText(_translate("MainWindow", "CheckBox Tristate"))
        self.check_box_3.setText(_translate("MainWindow", "CheckBox Disabled"))
        nonnull(self.tree_widget.headerItem()).setText(0, _translate("MainWindow", "qdz"))
        self.tree_widget.setSortingEnabled(False)
        nonnull(self.tree_widget.topLevelItem(0)).setText(0, _translate("MainWindow", "qzd"))
        nonnull(self.tree_widget.topLevelItem(1)).setText(0, _translate("MainWindow", "effefe"))
        self.tree_widget.setSortingEnabled(True)
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3v2), _translate("MainWindow", "Tab 3"))
        self.group_box_3v2.setTitle(_translate("MainWindow", "GroupBox v2"))
        self.push_button_2.setText(_translate("MainWindow", "PushButton"))
        self.bt_delay_popup.setText(_translate("MainWindow", "Delayed popup  "))
        self.bt_instant_popup.setText(_translate("MainWindow", "Instant popup"))
        self.bt_menu_button_popup.setText(_translate("MainWindow", "MenuButtonPopup"))
        self.push_button_3.setText(_translate("MainWindow", "Disabled"))
        self.tool_button.setText(_translate("MainWindow", "..."))
        self.menu_menu.setTitle(_translate("MainWindow", "&Menu"))
        self.menu_submenu_2.setTitle(_translate("MainWindow", "&Submenu 2"))
        self.dock_widget1.setWindowTitle(_translate("MainWindow", "&Dock widget 1"))
        self.combo_box.setItemText(0, _translate("MainWindow", "Item 0"))
        self.combo_box.setItemText(1, _translate("MainWindow", "Item 2"))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dock_widget2.setWindowTitle(_translate("MainWindow", "Dock widget &2"))
        self.action_action.setText(_translate("MainWindow", "&Action"))
        self.action_sub_menu.setText(_translate("MainWindow", "&Action B"))
        self.action_sub_menu.setToolTip(_translate("MainWindow", "submenu"))
        self.action_action_c.setText(_translate("MainWindow", "Action &C"))

    def about(self) -> None:
        Qt.QtWidgets.QMessageBox.aboutQt(self.central_widget, "About Menu")

    def critical(self) -> None:
        Qt.QtWidgets.QMessageBox.critical(self.central_widget, "Error", "Critical Error")
