'''
    issue_128
    =========

    Testing file for UI rendering issues.
'''

import os
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QFile, QTextStream

home = os.path.dirname(os.path.realpath(__file__))
project = os.path.dirname(os.path.dirname(home))
sys.path.append(os.path.join(project, 'resources'))
import breeze_pyqt5 as _  # noqa


class Ui_FunctionDisplayOptions(object):
    def setupUi(self, FunctionDisplayOptions):
        FunctionDisplayOptions.setObjectName("FunctionDisplayOptions")
        FunctionDisplayOptions.resize(377, 734)
        self.verticalLayout = QtWidgets.QVBoxLayout(FunctionDisplayOptions)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(FunctionDisplayOptions)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 377, 685))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.largeFormulaEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.largeFormulaEdit.sizePolicy().hasHeightForWidth())
        self.largeFormulaEdit.setSizePolicy(sizePolicy)
        self.largeFormulaEdit.setObjectName("largeFormulaEdit")
        self.verticalLayout_6.addWidget(self.largeFormulaEdit)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.parametersEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.parametersEdit.setObjectName("parametersEdit")
        self.verticalLayout_6.addWidget(self.parametersEdit)
        self.displayBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayBox.sizePolicy().hasHeightForWidth())
        self.displayBox.setSizePolicy(sizePolicy)
        self.displayBox.setObjectName("displayBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.displayBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.displayBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.scaleX = QtWidgets.QDoubleSpinBox(self.displayBox)
        self.scaleX.setMinimum(-100.0)
        self.scaleX.setMaximum(100.0)
        self.scaleX.setSingleStep(0.5)
        self.scaleX.setProperty("value", 0.0)
        self.scaleX.setObjectName("scaleX")
        self.horizontalLayout_3.addWidget(self.scaleX)
        self.scaleY = QtWidgets.QDoubleSpinBox(self.displayBox)
        self.scaleY.setMinimum(-100.0)
        self.scaleY.setMaximum(100.0)
        self.scaleY.setSingleStep(0.5)
        self.scaleY.setProperty("value", 0.0)
        self.scaleY.setObjectName("scaleY")
        self.horizontalLayout_3.addWidget(self.scaleY)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.displayBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.originX = QtWidgets.QDoubleSpinBox(self.displayBox)
        self.originX.setEnabled(True)
        self.originX.setMinimum(-100.0)
        self.originX.setMaximum(100.0)
        self.originX.setSingleStep(0.1)
        self.originX.setProperty("value", 0.0)
        self.originX.setObjectName("originX")
        self.horizontalLayout_2.addWidget(self.originX)
        self.originY = QtWidgets.QDoubleSpinBox(self.displayBox)
        self.originY.setEnabled(True)
        self.originY.setMinimum(-100.0)
        self.originY.setMaximum(100.0)
        self.originY.setSingleStep(0.1)
        self.originY.setProperty("value", 0.0)
        self.originY.setObjectName("originY")
        self.horizontalLayout_2.addWidget(self.originY)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.centeredX = QtWidgets.QCheckBox(self.displayBox)
        self.centeredX.setObjectName("centeredX")
        self.horizontalLayout_6.addWidget(self.centeredX)
        self.centeredY = QtWidgets.QCheckBox(self.displayBox)
        self.centeredY.setChecked(True)
        self.centeredY.setObjectName("centeredY")
        self.horizontalLayout_6.addWidget(self.centeredY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.displayImaginary = QtWidgets.QCheckBox(self.displayBox)
        self.displayImaginary.setObjectName("displayImaginary")
        self.verticalLayout_3.addWidget(self.displayImaginary)
        self.autoScrollOnPlayback = QtWidgets.QCheckBox(self.displayBox)
        self.autoScrollOnPlayback.setObjectName("autoScrollOnPlayback")
        self.verticalLayout_3.addWidget(self.autoScrollOnPlayback)
        self.verticalLayout_6.addWidget(self.displayBox)
        self.playbackBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.playbackBox.setObjectName("playbackBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.playbackBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.speedLbl = QtWidgets.QLabel(self.playbackBox)
        self.speedLbl.setObjectName("speedLbl")
        self.horizontalLayout_5.addWidget(self.speedLbl)
        self.speed = QtWidgets.QDoubleSpinBox(self.playbackBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setMaximum(1000.0)
        self.speed.setSingleStep(0.1)
        self.speed.setProperty("value", 1.0)
        self.speed.setObjectName("speed")
        self.horizontalLayout_5.addWidget(self.speed)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.playbackBox)
        self.displayBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.displayBox_2.setObjectName("displayBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.displayBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.displayBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.resolution = QtWidgets.QSpinBox(self.displayBox_2)
        self.resolution.setEnabled(True)
        self.resolution.setMaximum(48000)
        self.resolution.setObjectName("resolution")
        self.horizontalLayout_17.addWidget(self.resolution)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_13 = QtWidgets.QLabel(self.displayBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13)
        self.interpolation = QtWidgets.QSpinBox(self.displayBox_2)
        self.interpolation.setEnabled(True)
        self.interpolation.setMaximum(7)
        self.interpolation.setObjectName("interpolation")
        self.horizontalLayout_19.addWidget(self.interpolation)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_14 = QtWidgets.QLabel(self.displayBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        self.periodic = QtWidgets.QDoubleSpinBox(self.displayBox_2)
        self.periodic.setEnabled(True)
        self.periodic.setDecimals(3)
        self.periodic.setMaximum(88200.0)
        self.periodic.setObjectName("periodic")
        self.horizontalLayout_20.addWidget(self.periodic)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.displayBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.buffered = QtWidgets.QCheckBox(self.displayBox_2)
        self.buffered.setObjectName("buffered")
        self.horizontalLayout_18.addWidget(self.buffered)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6.addWidget(self.displayBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(FunctionDisplayOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_7.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.verticalLayout_7)

        self.retranslateUi(FunctionDisplayOptions)
        self.buttonBox.accepted.connect(FunctionDisplayOptions.accept)  # type: ignore
        self.buttonBox.rejected.connect(FunctionDisplayOptions.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FunctionDisplayOptions)

    def retranslateUi(self, FunctionDisplayOptions):
        _translate = QtCore.QCoreApplication.translate
        FunctionDisplayOptions.setWindowTitle(_translate("FunctionDisplayOptions", "Dialog"))
        self.label_3.setText(_translate("FunctionDisplayOptions", "parameters:"))
        self.displayBox.setTitle(_translate("FunctionDisplayOptions", "display"))
        self.label_2.setText(_translate("FunctionDisplayOptions", "scale"))
        self.scaleX.setToolTip(_translate("FunctionDisplayOptions", "Scaling of X-Axis as a power of 2"))
        self.scaleY.setToolTip(_translate("FunctionDisplayOptions", "Scaling of Y-Axis as a power of 2"))
        self.label.setText(_translate("FunctionDisplayOptions", "origin"))
        self.centeredX.setText(_translate("FunctionDisplayOptions", "x-axis centered"))
        self.centeredY.setText(_translate("FunctionDisplayOptions", "y-axis centered"))
        self.displayImaginary.setText(_translate("FunctionDisplayOptions", "display imaginary part"))
        self.autoScrollOnPlayback.setText(_translate("FunctionDisplayOptions", "scroll on playback"))
        self.playbackBox.setTitle(_translate("FunctionDisplayOptions", "playback"))
        self.speedLbl.setText(_translate("FunctionDisplayOptions", "speed factor"))
        self.displayBox_2.setTitle(_translate("FunctionDisplayOptions", "resolution / caching"))
        self.label_11.setText(_translate("FunctionDisplayOptions", "resolution"))
        self.label_13.setText(_translate("FunctionDisplayOptions", "interpolation"))
        self.label_14.setText(_translate("FunctionDisplayOptions", "periodic"))
        self.label_12.setText(_translate("FunctionDisplayOptions", "buffered"))
        self.buffered.setText(_translate("FunctionDisplayOptions", "on / off"))


def load_stylesheet(app):
    file = QFile(":/dark/stylesheet.qss")
    file.open(QFile.ReadOnly | QFile.Text)
    stream = QTextStream(file)
    app.setStyleSheet(stream.readAll())


app = QtWidgets.QApplication(sys.argv)
load_stylesheet(app)
dialog = QtWidgets.QDialog()
ui = Ui_FunctionDisplayOptions()
ui.setupUi(dialog)
dialog.show()
app.exec_()
