name: CMake

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install xvfb
        sudo apt-get install build-essential libgl1-mesa-dev libgstreamer-gl1.0-0 libpulse-dev \
            libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
            libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 \
            libxcb-xinerama0 libxcb1 libxkbcommon-dev libxkbcommon-x11-0 libxcb-xkb-dev cmake
        sudo apt install qt6-base-dev qtbase5-dev libqt5svg5-dev qt6-svg-dev
    - name: Running our CMake flow.
      run: |
        scripts/cmake.sh
