name: Configure

on: [push, pull_request]

jobs:
  theme-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PySide2 PySide6 PyQt5 PyQt6
    - name: Checking our configuration scripts.
      run: |
        scripts/configure.sh
