name: Linters

on: [pull_request, workflow_dispatch]

jobs:
  lint-python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      shell: bash
      run: |
        pipx install uv
        export PATH="${HOME}/.local/bin:${PATH}"
        uv tool install poethepoet
        uv tool install ruff
    - name: Analyzing the code with Ruff
      shell: bash
      run: |
        export PATH="${HOME}/.local/bin:${PATH}"
        uvx --from poethepoet poe lint
        uvx --from poethepoet poe type
    - name: Analyzing the examples with Ruff
      shell: bash
      if: ${{ matrix.os != 'macos-latest' }}
      run: |
        export PATH="${HOME}/.local/bin:${PATH}"
        cd example
        uvx --from poethepoet poe lint
        uvx --from poethepoet poe type

  lint-cpp:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        pipx install clang-tidy
    - name: Analysing the code with clang-tidy
      shell: bash
      run: |
        set -eux pipefail

        export PATH="${HOME}/.local/bin:${PATH}"

        # Windows oddly requires C++20 support due to internal bugs.
        if [[ "${RUNNER_OS}" == "Windows" ]]; then
          extra_args="-extra-arg=-std=c++20"
          passthrough=""
        elif [[ "${RUNNER_OS}" == "macOS" ]]; then
          # NOTE: The search paths aren't added by default, and we need C then C++ by default
          # for our search. This makes the process easier.
          extra_args="-extra-arg=-std=c++17 -extra-arg=--stdlib=libc++"
          location="$(xcrun --show-sdk-path)"
          passthrough="-I${location}/usr/include/c++/v1 -I${location}/usr/include"
        else
          extra_args="-extra-arg=-std=c++17"
          passthrough=""
        fi
        clang-tidy -checks=-*,clang-analyzer-*,-clang-analyzer-cplusplus* ${extra_args} example/cpp/detect/system_theme.hpp -- ${passthrough}
