name: Linters

on: [push]

jobs:
  lint-version-python:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pyright
    - name: Analysing the code with pylint
      run: |
        scripts/lint.sh

  lint-os-python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pyright
    - name: Analysing the code with pylint
      run: |
        scripts/lint.sh

  lint-cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang-tidy -y
    - name: Analysing the code with clang-tidy
      shell: bash
      run: |
        set -eux pipefail
        clang-tidy -checks=-*,clang-analyzer-*,-clang-analyzer-cplusplus* example/breeze_theme.hpp --
