name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        # NOTE: Add other OS's if required, but this should be cross-platform.
        os: [ubuntu-latest]
        # NOTE: Github doesn't support 3.7
        python-version: ["3.8", "3.10", "3.11", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      shell: bash
      run: |
        pipx install uv
        export PATH="${HOME}/.local/bin:${PATH}"
    - name: Run the test suite
      shell: bash
      run: |
        export PATH="${HOME}/.local/bin:${PATH}"
        uv run --group test pytest
