name: Theme

on: [push]

jobs:
  theme-python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [[ "$RUNNER_OS" == "Windows" ]]; then
            python -m pip install winrt-Windows.UI.ViewManagement winrt-Windows.UI
        fi
    - name: Checking our Python imports.
      run: |
        scripts/theme.sh
